/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Animacion;

import AñadirObjetos.AñadirVuelos;
import com.mycompany.InterfazGráfica.ModuloAdministración.Operador;
import com.mycompany.Objetos.VUELO;
import java.awt.event.KeyEvent;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Oscar Luna
*/
public class VueloAviones extends javax.swing.JFrame {
    
    private VUELO vuelo;
    private Operador vent;

    /**
     * Creates new form VueloAviones
     */
    public VueloAviones(VUELO vuelo, Operador vent) {
        initComponents();
        panel.setFocusable(true);
        ImageIcon avion = new ImageIcon("avion.png");
        ImageIcon aeropuertoicono = new ImageIcon("aeropuerto.png");
        lb.setIcon(avion);
        AeropuertoOrigen.setIcon(aeropuertoicono);
        AeropuertoDestino.setIcon(aeropuertoicono);
        if (vuelo!= null){
            //edición 
            this.NombreAeropuertoOrigen.setText(String.valueOf(vuelo.getNOMBRE_AEROPUERTO_ORIGEN()));
            this.NombreAeropuertoDestino.setText(String.valueOf(vuelo.getNOMBRE_AEROPUERTO_DESTINO())); 
        }
        this.setVisible(true);
         }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        lb = new javax.swing.JLabel();
        AeropuertoDestino = new javax.swing.JLabel();
        AeropuertoOrigen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombreAeropuertoOrigen = new javax.swing.JLabel();
        NombreAeropuertoDestino = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel.setToolTipText("VUELO EN PROCESO");
        panel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                panelKeyTyped(evt);
            }
        });

        lb.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("VUELO EN PROCESO");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(AeropuertoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreAeropuertoDestino)
                            .addComponent(AeropuertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(NombreAeropuertoOrigen)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreAeropuertoOrigen)
                    .addComponent(NombreAeropuertoDestino))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(AeropuertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(AeropuertoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelKeyPressed
        // TODO add your handling code here:
        int y=lb.getY();
        int x= lb.getX();   
        
        switch(evt.getExtendedKeyCode()){
            case KeyEvent.VK_UP:
                lb.setLocation(x, y-4);
                break;
            case KeyEvent.VK_DOWN:
                lb.setLocation(x, y+4);
                break;
            case KeyEvent.VK_LEFT:
                lb.setLocation(x-6, y);
                break;
            case KeyEvent.VK_RIGHT:
                    x=lb.getX();
                   lb.setLocation(x+10, y);
                   if(x>=530){
                       this.hide();
                       JOptionPane.showMessageDialog(null, "El Vuelo se ha completado");
                   }
                System.out.println(lb.getLocation());
                
                break;
               
        } 
    }//GEN-LAST:event_panelKeyPressed

    private void panelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_panelKeyTyped

    private void AcabarLaAnimación(int segundos) {
		try {
			Thread.sleep(segundos * 1000);
                        setVisible(false);
		} catch (InterruptedException ex) {
			Thread.currentThread().interrupt();
		}
	}
    private void TiempoIntermedio(){
        try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(VueloAviones.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AeropuertoDestino;
    private javax.swing.JLabel AeropuertoOrigen;
    private javax.swing.JLabel NombreAeropuertoDestino;
    private javax.swing.JLabel NombreAeropuertoOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
