/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AñadirObjetos;

import ManejadoresDeDatos.ImportExportAerolinea;
import ManejadoresDeDatos.ImportExportAviones;
import com.mycompany.Abstracts.AEROPUERTO;
import com.mycompany.InterfazGráfica.ModuloAdministración.Administracion;
import com.mycompany.InterfazGráfica.ModuloUsuario.Principal;
import com.mycompany.Objetos.AEROLINEA;
import com.mycompany.Objetos.DISTANCIA;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Oscar Luna
 */
public class AñadirDistancia extends javax.swing.JFrame {
//Aeropuerto
    private static Vector listaAerolineas = new Vector();
    private Vector NombreAeropuertos = new Vector();
    private AEROPUERTO Aeropuerto;
    private AEROPUERTO aeropuertoelegido1;
    private AEROPUERTO aeropuertoelegido2;
    private Administracion admin;
    private DISTANCIA distancia;
    private AñadirAerolinea añadirAerolinea;
    private Principal principal;
    
    //Aerolinea
    public void actualizarAerolinea(String AEROPUERTO, String NOMBRE_AEROLINEA){
        if (AEROPUERTO!=null)
        listaAerolineas.add(new AEROLINEA(AEROPUERTO,NOMBRE_AEROLINEA) {});
        
    }
    /**
     * Creates new form AñadirAerolinea
     */
    public AñadirDistancia(DISTANCIA distancia,Administracion admin) {
        initComponents();
        this.setVisible(true);
        
                if (Aeropuerto!= null){
            //edición 
            this.AeropuertosOrigenCombobox.setSelectedItem(Aeropuerto.getNOMBRE_AEROPUERTO());
            this.AeropuertoActualCombobox.setSelectedItem(Aeropuerto.getNOMBRE_AEROPUERTO());
            this.DistanciaMillas.setText("");

            
            //Obtener Fecha de Nacimiento
            }else {
                    this.AeropuertosOrigenCombobox.setSelectedItem("");
            this.AeropuertoActualCombobox.setSelectedItem("");
            this.DistanciaMillas.setText("");

       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CrearVuelo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        AeropuertoActualCombobox = new javax.swing.JComboBox<>(admin.getListaAeropuertos());
        jLabel3 = new javax.swing.JLabel();
        DistanciaMillas = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        AeropuertosOrigenCombobox = new javax.swing.JComboBox(admin.getListaAeropuertos());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AÑADIR AVIONES");

        CrearVuelo.setBackground(new java.awt.Color(153, 204, 255));
        CrearVuelo.setForeground(new java.awt.Color(0, 0, 0));
        CrearVuelo.setText("Guardar Distancia");
        CrearVuelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearVueloMouseClicked(evt);
            }
        });

        jLabel2.setText("Aeropuerto Actual:");

        jLabel3.setText(" Cantidad De Millas");

        DistanciaMillas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("AÑADIR O CARGAR AVIONES");

        jLabel15.setText("Nombre Aeropuerto Origen:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(235, 235, 235))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(8, 8, 8))
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DistanciaMillas, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AeropuertoActualCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(AeropuertosOrigenCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(CrearVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel7)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AeropuertosOrigenCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AeropuertoActualCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DistanciaMillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(CrearVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearVueloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearVueloMouseClicked
        // TODO add your handling code here:
        //Aerolinea Destino
        aeropuertoelegido1 = (AEROPUERTO) AeropuertosOrigenCombobox.getSelectedItem();
        //Aeropuerto Destino
        aeropuertoelegido2 = (AEROPUERTO) AeropuertoActualCombobox.getSelectedItem();

        //Añadir
        Administracion.actualizarDistancia(aeropuertoelegido1.getNOMBRE_AEROPUERTO(), aeropuertoelegido2.getNOMBRE_AEROPUERTO(), Integer.valueOf(DistanciaMillas.getText()));
        JOptionPane.showMessageDialog(null, "Distancia EStablecida con exito con éxito");

        this.dispose();
        
    }//GEN-LAST:event_CrearVueloMouseClicked

    /**
     * @param args the command line arguments
     */
    

    public static Vector getListaAerolineas() {
        return listaAerolineas;
    }

    public static void setListaAerolineas(Vector listaAerolineas) {
        AñadirDistancia.listaAerolineas = listaAerolineas;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AeropuertoActualCombobox;
    private javax.swing.JComboBox<String> AeropuertosOrigenCombobox;
    private javax.swing.JButton CrearVuelo;
    private javax.swing.JFormattedTextField DistanciaMillas;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
